/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.alx.kpij.Bmi;

import java.awt.Color;

/**
 *
 * @author Adi
 */
public class BMI extends javax.swing.JFrame {

    /**
     * Creates new form BMI
     */
    public BMI() {
        initComponents();
        this.setLocation(300, 200);
        this.getContentPane().setBackground(new Color(20, 230, 35));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        heightField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kalkulator BMI");

        genderComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kobieta", "Mężczyzna" }));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Wybierz płeć");
        jLabel2.setPreferredSize(new java.awt.Dimension(135, 22));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Waga w kg");
        jLabel3.setPreferredSize(new java.awt.Dimension(135, 22));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Podaj wiek");
        jLabel4.setMaximumSize(new java.awt.Dimension(135, 22));
        jLabel4.setPreferredSize(new java.awt.Dimension(135, 22));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Wzrost w metrach");
        jLabel5.setPreferredSize(new java.awt.Dimension(135, 22));

        ageField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ageField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ageField.setPreferredSize(new java.awt.Dimension(135, 28));

        heightField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        heightField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        heightField.setPreferredSize(new java.awt.Dimension(135, 28));

        weightField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        weightField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        weightField.setPreferredSize(new java.awt.Dimension(135, 28));

        resultArea.setColumns(20);
        resultArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Wynik:");

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Policz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ageField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(heightField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(weightField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(116, 116, 116))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (genderComboBox.getSelectedIndex() == 0){
            woman();
        } else if (genderComboBox.getSelectedIndex() == 1){
            man();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void man(){
        try {
            double age = Double.parseDouble(ageField.getText());
            double height = Double.parseDouble(heightField.getText());
            double weight = Double.parseDouble(weightField.getText());
            double result = weight / (Math.pow(height, 2.0));
            String resultString = String.format(" %.1f", result);
            if (age < 15 ){
                resultArea.setForeground(Color.BLUE);
                resultArea.setText("Wskaźnika BMI nie powinno się stosować dla dzieci.");
            } else if (age >= 15 && age < 25){
                if (result < 19 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinieneś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 19-24.");
                } else if (result >= 19 && result < 24){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 24 && result < 29){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 19-24.");
                }else if (result >= 29 && result < 39){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinieneś przejść na dietę nisko kaloryczną.\nPowinieneś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 19-24.");
                }else if (result >= 39){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 19-24.");
                }
            }else if (age >= 25 && age < 35){
                if (result < 20 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinieneś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 20-25.");
                } else if (result >= 20 && result < 25){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 25 && result < 30){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 20-25.");
                }else if (result >= 30 && result < 40){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinieneś przejść na dietę nisko kaloryczną.\nPowinieneś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 20-25.");
                }else if (result >= 40){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 20-25.");
                }
            }else if (age >= 35 && age < 45){
                if (result < 21 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinieneś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 21-26.");
                } else if (result >= 21 && result < 26){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 26 && result < 31){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 21-26.");
                }else if (result >= 31 && result < 41){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinieneś przejść na dietę nisko kaloryczną.\nPowinieneś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 21-26.");
                }else if (result >= 41){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 21-26.");
                }
            }else if (age >= 45 && age < 55){
                if (result < 22 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinieneś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 22-27.");
                } else if (result >= 22 && result < 27){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 27 && result < 32){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 22-27.");
                }else if (result >= 32 && result < 42){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinieneś przejść na dietę nisko kaloryczną.\nPowinieneś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 22-27.");
                }else if (result >= 42){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 22-27.");
                }
            }else if (age >= 55 && age < 65){
                if (result < 23 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinieneś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 23-28.");
                } else if (result >= 23 && result < 28){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 28 && result < 33){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 23-28.");
                }else if (result >= 33 && result < 43){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinieneś przejść na dietę nisko kaloryczną.\nPowinieneś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 23-28.");
                }else if (result >= 43){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 23-28.");
                }
            }else if (age >= 65){
                if (result < 24 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinieneś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 24-29.");
                } else if (result >= 24 && result < 29){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 29 && result < 34){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 24-29.");
                }else if (result >= 34 && result < 44){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinieneś przejść na dietę nisko kaloryczną.\nPowinieneś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 24-29.");
                }else if (result >= 44){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 24-29.");
                }
            }
            
        } catch (NumberFormatException e){
            resultArea.setForeground(Color.RED);
            resultArea.setText("Podano złe wartości liczbowe!!!\nSprawdź i spróbuj ponownie.");
        }
    }
    public void woman(){
        try {
            double age = Double.parseDouble(ageField.getText());
            double height = Double.parseDouble(heightField.getText());
            double weight = Double.parseDouble(weightField.getText());
            double result = weight / (Math.pow(height, 2.0));
            String resultString = String.format(" %.1f", result);
            if (age < 15 ){
                resultArea.setForeground(Color.BLUE);
                resultArea.setText("Wskaźnika BMI nie powinno się stosować dla dzieci.");
            } else if (age >= 15 && age < 25){
                if (result < 20 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinnaś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 20-25.");
                } else if (result >= 20 && result < 25){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 25 && result < 30){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 20-25.");
                }else if (result >= 30 && result < 40){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinnaś przejść na dietę nisko kaloryczną.\nPowinnaś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 20-25.");
                }else if (result >= 40){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 20-25.");
                }
            }else if (age >= 25 && age < 35){
                if (result < 21 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinnaś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 21-26.");
                } else if (result >= 21 && result < 26){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 26&& result < 31){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 21-26.");
                }else if (result >= 31 && result < 41){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinnaś przejść na dietę nisko kaloryczną.\nPowinnaś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 21-26.");
                }else if (result >= 41){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 21-26.");
                }
            }else if (age >= 35 && age < 45){
                if (result < 22 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinnaś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 22-27.");
                } else if (result >= 22 && result < 27){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 27 && result < 32){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 22-27.");
                }else if (result >= 32 && result < 42){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinnaś przejść na dietę nisko kaloryczną.\nPowinnaś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 22-27.");
                }else if (result >= 42){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 22-27.");
                }
            }else if (age >= 45 && age < 55){
                if (result < 23 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinnaś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 23-28.");
                } else if (result >= 23 && result < 28){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 28 && result < 33){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 23-28.");
                }else if (result >= 33 && result < 43){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinnaś przejść na dietę nisko kaloryczną.\nPowinnaś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 23-28.");
                }else if (result >= 43){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 23-28.");
                }
            }else if (age >= 55 && age < 65){
                if (result < 24 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinnaś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 24-29.");
                } else if (result >= 24 && result < 29){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 29 && result < 34){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 24-29.");
                }else if (result >= 34 && result < 44){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinnaś przejść na dietę nisko kaloryczną.\nPowinnaś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 24-29.");
                }else if (result >= 44){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 24-29.");
                }
            }else if (age >= 65){
                if (result < 25 ){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nNiedowaga. Powinnaś trochę przybrać na wadze.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 25-30.");
                } else if (result >= 25 && result < 30){
                    resultArea.setForeground(Color.GREEN);
                    resultArea.setText("Twój wynik to: " + resultString + "\nBrawo twój wskaźnik mieści się w normie.\nTak trzymaj.");
                }else if (result >= 30 && result < 35){
                    resultArea.setForeground(Color.BLUE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nMasz nadwagę.\nZacznij zwracać uwagę na to co i w jakich ilościach jesz.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 25-30.");
                }else if (result >= 35 && result < 45){
                    resultArea.setForeground(Color.ORANGE);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na otyłość.\nPowinnaś przejść na dietę nisko kaloryczną.\nPowinnaś też zwiększyć aktywność fizyczną.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 25-30.");
                }else if (result >= 45){
                    resultArea.setForeground(Color.RED);
                    resultArea.setText("Twój wynik to: " + resultString + "\nTwój wskaźnik wskazuję na skrajną otyłość.\nZgłoś się do lekarza i dietetyka.\nKoniecznie zacznij regularnie ćwiczyć.\nPrawidłowy wskaźnik dla ciebie powinien się mieścić w zakresie 25-30.");
                }
            }
            
        } catch (NumberFormatException e){
            resultArea.setForeground(Color.RED);
            resultArea.setText("Podano złe wartości liczbowe!!!\nSprawdź i spróbuj ponownie.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField heightField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
